### PR TITLE
feat: apply flip on cvv focus

### PR DESCRIPTION
**Pull request by riandy-dimas**
This PR is related to issue #10

Changelogs:
- Create `CardBodyBack` component
- Flip to `CardBodyBack` component when user focusing on CVV input field

Screen Recording 2020-10-05 at 14 36 14

### CODE REVIEW

**Comment by AliNisarAhmed** [comment]
Hi @riandy-dimas, Thank you for your contribution. PR looks good, but I added a prettier config file, please rebase master and format your code to match the styles. Then we can discuss the animation further.

**Comment by riandy-dimas** [comment]
@AliNisarAhmed I've rebased the master and merged it into my development branch. Btw my linter found that this one emits an error in `Form.tsx`, can help to check? The error was gone when I cast `StyledInput` into `any` like this `styled(StyledInput as any)`.
image

**Comment by AliNisarAhmed** [comment]
@riandy-dimas  Thanks for pointing that out. It was an error in an old version of `styled-components`. Updating it to v5 fixed the issue. So if you rebase now the error should be gone. Let me know when that is done...

**Comment by riandy-dimas** [comment]
@AliNisarAhmed done, I have rebased master and the issue gone.

**Pull request merged**
